name: nyxx_self
version: 5.0.1
description: The self-bot fork of nyxx, a simple, robust framework for creating discord bots for Dart language.
homepage: https://github.com/V3ntus/nyxx
repository: https://github.com/V3nuts/nyxx
documentation: https://nyxx.l7ssha.xyz
issue_tracker: https://github.com/V3ntus/nyxx/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  http: ^0.13.3
  logging: ^1.0.1
  path: ^1.8.3
  retry: ^3.1.0
  eterl: ^1.0.1

dev_dependencies:
  test: ^1.22.0
  mockito: ^5.0.16
  build_runner: ^2.3.0
  lints: ^2.0.0
